### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by comlit** [lavaloop-official/GovLearn#29]
wenn man feedback fpr einen kurs anfragt bekommt im moment nur die user id der review zurück 
![image](https://github.com/lavaloop-official/GovLearn/assets/67443177/3f7e1265-1c39-40ac-a84a-e692839178f8)
wäre nice wenn man da auch den namen hätte um den anzeigen zu können.

**Comment by Paramian** [comment]
Ist jetzt in dem neuen PR integriert :) -> Key: username
