### ISSUE TITLE
average feedback

### ISSUE THREAD

**Issue by comlit** [lavaloop-official/GovLearn#33]
endpunkt gibt 404 zurück wenn keine bewertungen für den kurs vorhanden ist. besser wäre eine leere liste😅
![image](https://github.com/lavaloop-official/GovLearn/assets/67443177/8d20b2d2-5a57-49c4-98f1-eeb102140a78)

**Comment by comlit** [comment]
Sehe gerade mit leere liste meinte ich einfach leere payload glaub ich

**Comment by Paramian** [comment]
Das kann ich gerne so implementieren^^. Nehme ich für morgen auf meine To-Do Liste

**Comment by comlit** [comment]
@Paramian hab das issue hier schon wieder ganz vergessen🙃ist das schon implementiert?
